### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by sojab0on** [brontide/aioedgeos#9]
when i run the setup.py on my ubuntu mashine witch has the docker for grafana on it it give an error 
setuptools not found 

what do i need to putwhere to get the stats in my grafana dashboard

**Comment by sojab0on** [comment]
also when i let it run the docker compose it spits out the following 
influx-edge2influx-1  | 2021-11-23 11:22:35,920:INFO:root:CONNECTING TO ROUTER https;//172.16.0.1:4443 with user michel
influx-edge2influx-1  | 2021-11-23 11:22:35,921:ERROR:root:Run of stay_logged_in raised exception
influx-edge2influx-1  | Traceback (most recent call last):
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 60, in run
influx-edge2influx-1  |     await self.call(*self.args, **self.kwargs)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 95, in stay_logged_in
influx-edge2influx-1  |     await edgeos.login()
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 170, in login
influx-edge2influx-1  |     async with self.session.post(f'{self.url}',
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1012, in __aenter__
influx-edge2influx-1  |     self._resp = await self._coro
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 464, in _request
influx-edge2influx-1  |     req = self._request_class(
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
influx-edge2influx-1  |     self.update_host(url)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
influx-edge2influx-1  |     raise InvalidURL(url)
influx-edge2influx-1  | aiohttp.client_exceptions.InvalidURL: https;//172.16.0.1:4443
influx-edge2influx-1  | Traceback (most recent call last):
influx-edge2influx-1  |   File "/app/influx.py", line 341, in <module>
influx-edge2influx-1  |     asyncio.run(main_loop())
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
influx-edge2influx-1  |     return loop.run_until_complete(main)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
influx-edge2influx-1  |     return future.result()
influx-edge2influx-1  |   File "/app/influx.py", line 241, in main_loop
influx-edge2influx-1  |     router = await stack.enter_async_context(
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/contextlib.py", line 556, in enter_async_context
influx-edge2influx-1  |     result = await _cm_type.__aenter__(cm)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 145, in __aenter__
influx-edge2influx-1  |     await self.setup()
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 134, in setup
influx-edge2influx-1  |     await self.stack.enter_async_context(TaskEvery(stay_logged_in, self, interval=300))
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/contextlib.py", line 556, in enter_async_context
influx-edge2influx-1  |     result = await _cm_type.__aenter__(cm)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 77, in __aenter__
influx-edge2influx-1  |     await self.run()
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 60, in run
influx-edge2influx-1  |     await self.call(*self.args, **self.kwargs)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 95, in stay_logged_in
influx-edge2influx-1  |     await edgeos.login()
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aioedgeos/api.py", line 170, in login
influx-edge2influx-1  |     async with self.session.post(f'{self.url}',
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1012, in __aenter__
influx-edge2influx-1  |     self._resp = await self._coro
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 464, in _request
influx-edge2influx-1  |     req = self._request_class(
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
influx-edge2influx-1  |     self.update_host(url)
influx-edge2influx-1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
influx-edge2influx-1  |     raise InvalidURL(url)
influx-edge2influx-1  | aiohttp.client_exceptions.InvalidURL: https;//172.16.0.1:4443
influx-edge2influx-1  | 2021-11-23 11:22:35,936:ERROR:asyncio:Unclosed client session
influx-edge2influx-1  | client_session: <aiohttp.client.ClientSession object at 0x7f56a46c9070>
influx-edge2influx-1 exited with code 1
root@kasm-web:/home/michel/Downloads/aioedgeos-0.1.1/examples/influ
what am i dooing wrong here

**Comment by 8chauser** [comment]
aiohttp.client_exceptions.InvalidURL: https;//172.16.0.1:4443

are you sure this location is reachable?
